[video]
extensions = [".mp4", ".mkv", ".avi", ".wmv", ".mov", ".flv", ".rmvb", ".rm", ".3gp", ".m4v", ".m2ts", ".ts", ".mpg"]
min_size_mb = 300

[image]
extensions = [".jpg", ".jpeg", ".png", ".gif", ".bmp", ".webp", ".tiff"]
valid_keywords = ["poster", "movie", "folder", "cover", "fanart", "banner", "clearart", "thumb", "landscape", "logo", "clearlogo", "disc", "discart", "backdrop", "keyart"]

[nfo]
match_length = 5

[rename]
pattern = "number2"

[cleanup]
delete_dir_name = ".delete"

[bigvideo]
dir_name = "BIG"
width_threshold = 2000

[actor]
unknown_category = "99"
japanese_category = "0"
title_max_length = 20

[movie]
force_reorganize = false

[plan]
batch_size = 200
